name: Primera prueba
run-name: Primera prueba en ejecución
on: [workflow_dispatch]
jobs:
  execution:
    name: small execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - name: run tests
        run: python -m unittest
      - name: run script
        run: |
          echo "Directory: ${{ github.workspace }}"
          python --version
          ls -l
          python hello.py
