name: Primera prueba
run-name: Primera prueba en ejecución
on: [workflow_dispatch]
jobs:
  execution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: run script
        run: |
          echo "${{ github.workspace }}"
#          python ${{ github.workspace }}/hello.py
