name: Primera prueba
run-name: Primera prueba en ejecución
on: [workflow_dispatch]
jobs:
  run-tests:
    name: running test suite
    runs-on: ubuntu-latest
    steps: 
      - name: run tests
        run: python -m unittest

  execution:
    name: small execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: run script
        run: |
          echo "Directory: ${{ github.workspace }}"
          python --version
          ls -l
          python hello.py
